# Generated by Django 4.1.6 on 2023-02-13 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test_manager', '0004_alltest_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Organization_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test_manager.alltest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
