# Generated by Django 4.1.6 on 2023-02-13 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization_test', '0003_usertestresult_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestresult',
            name='organise_test_slug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Organization_test.organisetest'),
        ),
    ]
