# Generated by Django 4.1.6 on 2023-02-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organize_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisetest',
            name='slug',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
