# Generated by Django 4.1.6 on 2023-02-08 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User_manager', '0001_initial'),
        ('Test_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=200, null=True, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('for_league', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='User_manager.league')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='Test_manager.questions')),
                ('question_possible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_possibles', to='Test_manager.questions')),
                ('right_answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='right_answers', to='Test_manager.questions')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test', to='Test_manager.alltest')),
            ],
        ),
    ]
