# Generated by Django 4.1.6 on 2023-02-13 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Test_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Question_manager', '0001_initial'),
        ('User_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questions',
            name='for_league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='User_manager.league'),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_correct_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_correct_answer', to='Question_manager.allpossibleanswers'),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_possible_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Question_manager.allpossibleanswers'),
        ),
        migrations.AddField(
            model_name='alltest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alltest',
            name='for_league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='User_manager.league'),
        ),
        migrations.AddField(
            model_name='alltest',
            name='questions',
            field=models.ManyToManyField(through='Test_manager.QuestionTest', to='Test_manager.questions'),
        ),
    ]
