# Generated by Django 4.1.6 on 2023-02-08 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test_manager', '0002_alltest_questiontest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontest',
            name='question_possible',
        ),
        migrations.RemoveField(
            model_name='questiontest',
            name='right_answer',
        ),
        migrations.AlterField(
            model_name='questiontest',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Test_manager.questions'),
        ),
        migrations.AlterField(
            model_name='questiontest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='Test_manager.alltest'),
        ),
    ]
