# Generated by Django 4.1.6 on 2023-02-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_manager', '0003_remove_questiontest_question_possible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltest',
            name='questions',
            field=models.ManyToManyField(through='Test_manager.QuestionTest', to='Test_manager.questions'),
        ),
    ]
